package prolab01.pkg2;

import javax.swing.Icon;
import javax.swing.ImageIcon;

public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        Secim1.setVisible(true);
        Secim2.setVisible(true);
        jLabel2.setVisible(false);
        Secim3.setVisible(false);
        Text1.setVisible(false);
        Text2.setVisible(false);
        Text3.setVisible(false);
        TextOyuncu.setVisible(false);
        
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jButton10.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Secim1 = new javax.swing.JButton();
        Secim2 = new javax.swing.JButton();
        Secim3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextOyuncu = new javax.swing.JTextField();
        Text1 = new javax.swing.JTextField();
        Text2 = new javax.swing.JTextField();
        Text3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Secim1.setBackground(new java.awt.Color(255, 0, 0));
        Secim1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Secim1.setText("Oyuncu vs. Bilgisayar");
        Secim1.setActionCommand("Secim2");
        Secim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Secim1ActionPerformed(evt);
            }
        });
        getContentPane().add(Secim1);
        Secim1.setBounds(360, 100, 210, 250);

        Secim2.setBackground(new java.awt.Color(255, 0, 0));
        Secim2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Secim2.setText("Bilgisayar vs. Bilgisayar");
        Secim2.setActionCommand("Secim3");
        Secim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Secim2ActionPerformed(evt);
            }
        });
        getContentPane().add(Secim2);
        Secim2.setBounds(700, 100, 210, 250);

        Secim3.setBackground(new java.awt.Color(255, 0, 0));
        Secim3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Secim3.setText("BAŞLA");
        Secim3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Secim3ActionPerformed(evt);
            }
        });
        getContentPane().add(Secim3);
        Secim3.setBounds(490, 400, 280, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/background.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        TextOyuncu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextOyuncuActionPerformed(evt);
            }
        });
        getContentPane().add(TextOyuncu);
        TextOyuncu.setBounds(10, 30, 130, 50);

        Text1.setEditable(false);
        Text1.setBackground(new java.awt.Color(0, 0, 255));
        Text1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text1ActionPerformed(evt);
            }
        });
        getContentPane().add(Text1);
        Text1.setBounds(140, 30, 140, 50);

        Text2.setEditable(false);
        Text2.setBackground(new java.awt.Color(255, 0, 0));
        Text2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Text2.setText("Bilgisayar");
        Text2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text2ActionPerformed(evt);
            }
        });
        getContentPane().add(Text2);
        Text2.setBounds(140, 630, 140, 50);

        Text3.setEditable(false);
        Text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text3ActionPerformed(evt);
            }
        });
        getContentPane().add(Text3);
        Text3.setBounds(400, 300, 490, 100);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 100, 200, 250);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 30, 200, 250);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(540, 30, 200, 250);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(740, 30, 200, 250);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1000, 120, 200, 250);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(80, 350, 200, 250);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(340, 410, 200, 250);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton8.setText("jButton8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(540, 410, 200, 250);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(740, 410, 200, 250);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/pokemon-card-back_600.jpg"))); // NOI18N
        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(1000, 370, 200, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pics/background2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 720);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //jButton1.setIcon(Pikachu.ikon);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void Secim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Secim1ActionPerformed
        // TODO add your handling code here:
        Secim1.setVisible(false);
        Secim2.setVisible(false);
        Secim3.setVisible(true);
        TextOyuncu.setVisible(true);
        Text2.setVisible(true);
        
    }//GEN-LAST:event_Secim1ActionPerformed

    private void Secim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Secim2ActionPerformed
        // TODO add your handling code here:
        Secim1.setVisible(false);
        Secim2.setVisible(false);
        Secim3.setVisible(true);
        Text1.setText("Bilgisayar-1");
        Text1.setVisible(true);
        Text2.setText("Bilgisayar-2");
        Text2.setVisible(true);
        
    }//GEN-LAST:event_Secim2ActionPerformed

    private void Secim3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Secim3ActionPerformed
        // TODO add your handling code here:
        
        Secim3.setVisible(false);
        jLabel1.setVisible(false);
        //jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        jLabel2.setVisible(true);
        
        
    }//GEN-LAST:event_Secim3ActionPerformed

    private void Text2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text2ActionPerformed

    private void Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text1ActionPerformed

    private void Text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text3ActionPerformed

    private void TextOyuncuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextOyuncuActionPerformed
        // TODO add your handling code here:
        String OyuncuAdi = TextOyuncu.getText();
        System.out.println(OyuncuAdi);
        Text1.setVisible(true);
        Text1.setText(OyuncuAdi);
        TextOyuncu.setVisible(false);
        
    }//GEN-LAST:event_TextOyuncuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Secim1;
    private javax.swing.JButton Secim2;
    private javax.swing.JButton Secim3;
    private javax.swing.JTextField Text1;
    private javax.swing.JTextField Text2;
    private javax.swing.JTextField Text3;
    private javax.swing.JTextField TextOyuncu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
